version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /code/cubrim-rs
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns: ["*"]
