#!/usr/bin/env python3
"""Assemble the CUBR-0074 real-world web corpus (v2).

Corpus v1 was project-authored: a generator produced fixtures that brotli-11
compresses to ratio 0.0079, a 126x compression no real stylesheet exhibits. Any
ratio measured against it says more about the generator than about the web, so
the decode-speed consilium made a real corpus Gate 1 for every claim.

This collector takes only bytes that are genuinely served on the web and that
we may legally redistribute:

* our own production site pages and API responses (Arcanada owns them, and they
  are already public);
* dist files and source maps from MIT-licensed packages, which are exactly the
  artefacts a real deployment ships;
* a real WOFF2 face under the SIL Open Font License, carried over from v1
  because it was already a real asset.

Two families are deliberately absent rather than faked. See MANIFEST_GAPS.

Every sample records where it came from, its licence, and its SHA-256. Sources
that must be fetched are pinned by digest on first collection, so a later run
that receives different bytes fails instead of silently redefining the corpus.

Usage:
  collect_real_world.py --out bench/web-corpus            # collect and write
  collect_real_world.py --out bench/web-corpus --check    # verify only
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess
import sys
import urllib.request

SCHEMA_VERSION = 2

# Content types the canon names that this corpus cannot yet source honestly.
# They are recorded, not filled with a fixture: a fabricated sample would
# reproduce exactly the defect that retired corpus v1.
MANIFEST_GAPS = [
    {
        "media_family": "wasm",
        "reason": (
            "No real WebAssembly module is available to redistribute. Cubrim "
            "itself does not yet build for wasm32-unknown-unknown (getrandom "
            "requires a JS feature), which is CUBR-0077's subject."
        ),
        "blocked_on": "CUBR-0077",
    },
    {
        "media_family": "svg",
        "reason": (
            "Our own production SVGs are ~300-byte inline icons, too small to "
            "form a size class, and the third-party SVGs available locally are "
            "vendor logos carrying trademark considerations a shipped corpus "
            "should not take on."
        ),
        "blocked_on": "operator sourcing decision",
    },
]

SITE = "https://cubrim.com"
API = "https://api.cubrim.com"

# Files copied from a local checkout. Path is resolved against --source-root.
LOCAL_SOURCES = [
    {
        "sample_id": "css-medium-tailwind-v2",
        "media_family": "css",
        "media_type": "text/css",
        "license_id": "MIT",
        "relative_path": "cubrim-site/CUBR-0074/css/tailwind.css",
        "source_ref": "arcanada:cubrim-site/css/tailwind.css (production stylesheet, Tailwind output)",
        "attribution": "Arcanada; generated by Tailwind CSS (MIT)",
    },
    {
        "sample_id": "javascript-small-resolve-uri-v2",
        "media_family": "javascript",
        "media_type": "text/javascript",
        "license_id": "MIT",
        "relative_path": "cubrim-site/CUBR-0074/node_modules/@jridgewell/resolve-uri/dist/resolve-uri.umd.js",
        "source_ref": "npm:@jridgewell/resolve-uri dist/resolve-uri.umd.js",
        "attribution": "Justin Ridgewell and contributors (MIT)",
    },
    {
        "sample_id": "javascript-medium-sourcemap-codec-v2",
        "media_family": "javascript",
        "media_type": "text/javascript",
        "license_id": "MIT",
        "relative_path": "cubrim-site/CUBR-0074/node_modules/@jridgewell/sourcemap-codec/dist/sourcemap-codec.umd.js",
        "source_ref": "npm:@jridgewell/sourcemap-codec dist/sourcemap-codec.umd.js",
        "attribution": "Justin Ridgewell and contributors (MIT)",
    },
    {
        "sample_id": "javascript-medium-magic-string-v2",
        "media_family": "javascript",
        "media_type": "text/javascript",
        "license_id": "MIT",
        "relative_path": "cubrim-site/CUBR-0074/node_modules/magic-string/dist/magic-string.umd.js",
        "source_ref": "npm:magic-string dist/magic-string.umd.js",
        "attribution": "Rich Harris and contributors (MIT)",
    },
    {
        "sample_id": "source-map-small-sourcemap-codec-v2",
        "media_family": "source-map",
        "media_type": "application/json",
        "license_id": "MIT",
        "relative_path": "cubrim-site/CUBR-0074/node_modules/@jridgewell/sourcemap-codec/dist/sourcemap-codec.umd.js.map",
        "source_ref": "npm:@jridgewell/sourcemap-codec dist/sourcemap-codec.umd.js.map",
        "attribution": "Justin Ridgewell and contributors (MIT)",
    },
    {
        "sample_id": "source-map-large-magic-string-v2",
        "media_family": "source-map",
        "media_type": "application/json",
        "license_id": "MIT",
        "relative_path": "cubrim-site/CUBR-0074/node_modules/magic-string/dist/magic-string.umd.js.map",
        "source_ref": "npm:magic-string dist/magic-string.umd.js.map",
        "attribution": "Rich Harris and contributors (MIT)",
    },
]

# Responses fetched from our own production surfaces.
FETCHED_SOURCES = [
    {
        "sample_id": "html-medium-home-v2",
        "media_family": "html",
        "media_type": "text/html",
        "license_id": "proprietary-arcanada-redistributable",
        "url": f"{SITE}/en/",
        "source_ref": "arcanada:cubrim.com/en/ (production HTML document)",
        "attribution": "Arcanada",
    },
    {
        "sample_id": "html-large-web-codec-v2",
        "media_family": "html",
        "media_type": "text/html",
        "license_id": "proprietary-arcanada-redistributable",
        "url": f"{SITE}/en/web-codec",
        "source_ref": "arcanada:cubrim.com/en/web-codec (production HTML document)",
        "attribution": "Arcanada",
    },
    {
        "sample_id": "json-api-small-hypotheses-v2",
        "media_family": "json-api",
        "media_type": "application/json",
        "license_id": "proprietary-arcanada-redistributable",
        "url": f"{API}/api/web-benchmark/hypotheses",
        "source_ref": "arcanada:api.cubrim.com/api/web-benchmark/hypotheses",
        "attribution": "Arcanada",
    },
    {
        "sample_id": "json-api-medium-web-benchmark-v2",
        "media_family": "json-api",
        "media_type": "application/json",
        "license_id": "proprietary-arcanada-redistributable",
        "url": f"{API}/api/web-benchmark",
        "source_ref": "arcanada:api.cubrim.com/api/web-benchmark",
        "attribution": "Arcanada",
    },
    {
        "sample_id": "json-api-large-world-benchmark-v2",
        "media_family": "json-api",
        "media_type": "application/json",
        "license_id": "proprietary-arcanada-redistributable",
        "url": f"{API}/api/world-benchmark",
        "source_ref": "arcanada:api.cubrim.com/api/world-benchmark",
        "attribution": "Arcanada",
    },
]

# Already a real asset in corpus v1; carried over unchanged.
CARRIED_OVER = [
    {
        "sample_id": "woff2-medium-inter-latin-v20",
        "media_family": "woff2",
        "media_type": "font/woff2",
        "license_id": "OFL-1.1",
        "relative_path": None,
        "source_ref": "Inter latin subset, carried over from web corpus v1",
        "attribution": "The Inter Project Authors (SIL Open Font License 1.1)",
    },
]

SIZE_CLASS_BOUNDS = {
    "small": (1, 10_240),
    "medium": (10_240, 102_400),
    "large": (102_400, 8 * 1024 * 1024),
}


def digest(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def fetch(url: str) -> bytes:
    request = urllib.request.Request(
        url,
        headers={
            # Ask for the identity encoding: the corpus stores the resource,
            # not somebody else's compression of it.
            "Accept-Encoding": "identity",
            "User-Agent": "cubrim-web-corpus/2 (+https://cubrim.com)",
        },
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        if response.status != 200:
            raise RuntimeError(f"{url} returned {response.status}")
        return response.read()


def classify(byte_count: int) -> str:
    """Derive the size class. A sample outside every band is a real error."""
    for name, (low, high) in SIZE_CLASS_BOUNDS.items():
        if low <= byte_count < high:
            return name
    raise RuntimeError(f"{byte_count} bytes falls outside every size class")


def brotli_ratio(payload: bytes) -> float:
    """A realism signal, not a benchmark result.

    Corpus v1's defect was visible here: brotli-11 reached 0.0079 on its CSS
    sample. Real text resources land around 0.15-0.30, so a ratio far below
    that means the sample is synthetic rather than representative.
    """
    result = subprocess.run(
        ["brotli", "-q", "11", "-c"], input=payload, capture_output=True, check=True
    )
    return len(result.stdout) / len(payload)


def build(out_root: pathlib.Path, source_root: pathlib.Path, check_only: bool) -> int:
    payloads_dir = out_root / "payloads-v2"
    previous_manifest = out_root / "manifest.v2.json"
    pinned: dict[str, str] = {}
    if previous_manifest.is_file():
        for entry in json.loads(previous_manifest.read_text())["samples"]:
            pinned[entry["sample_id"]] = entry["sha256"]

    if not check_only:
        payloads_dir.mkdir(parents=True, exist_ok=True)

    samples = []
    failures = []

    for spec in LOCAL_SOURCES:
        source = source_root / spec["relative_path"]
        if not source.is_file():
            failures.append(f"{spec['sample_id']}: missing local source {source}")
            continue
        samples.append((spec, source.read_bytes(), f"payloads-v2/{source.name}"))

    for spec in FETCHED_SOURCES:
        try:
            payload = fetch(spec["url"])
        except Exception as error:  # noqa: BLE001 - reported, not swallowed
            failures.append(f"{spec['sample_id']}: fetch failed: {error}")
            continue
        suffix = {"html": ".html", "json-api": ".json"}[spec["media_family"]]
        samples.append((spec, payload, f"payloads-v2/{spec['sample_id']}{suffix}"))

    for spec in CARRIED_OVER:
        legacy = out_root / "payloads" / "inter-latin.medium.woff2"
        if not legacy.is_file():
            candidates = sorted((out_root / "payloads").glob("*.woff2"))
            if not candidates:
                failures.append(f"{spec['sample_id']}: no woff2 in corpus v1")
                continue
            legacy = candidates[0]
        samples.append((spec, legacy.read_bytes(), f"payloads-v2/{legacy.name}"))

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        return 1

    records = []
    for spec, payload, relative in samples:
        sha = digest(payload)
        sample_id = spec["sample_id"]
        if sample_id in pinned and pinned[sample_id] != sha:
            print(
                f"FAIL: {sample_id} changed since it was pinned "
                f"({pinned[sample_id][:12]} -> {sha[:12]}). A corpus sample is "
                "immutable; add a new sample id instead.",
                file=sys.stderr,
            )
            return 1
        try:
            size_class = classify(len(payload))
        except RuntimeError as error:
            print(f"FAIL: {sample_id}: {error}", file=sys.stderr)
            return 1

        if not check_only:
            (out_root / relative).write_bytes(payload)

        records.append(
            {
                "sample_id": sample_id,
                "path": relative,
                "media_family": spec["media_family"],
                "media_type": spec["media_type"],
                "size_class": size_class,
                "byte_count": len(payload),
                "sha256": sha,
                "license_id": spec["license_id"],
                "attribution": spec["attribution"],
                "redistributable": True,
                "source_ref": spec["source_ref"],
            }
        )

    records.sort(key=lambda entry: entry["sample_id"])
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "corpus_key": "cubr0074-web-real-v2",
        "provenance": {
            "collector": "bench/web-corpus/collect_real_world.py",
            "policy": (
                "Real bytes served on the web that we may redistribute. No "
                "generated fixtures. Absent content types are recorded as gaps."
            ),
        },
        "gaps": MANIFEST_GAPS,
        "samples": records,
    }

    if not check_only:
        previous_manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
        checksums = out_root / "MANIFEST-V2.sha256"
        checksums.write_text(
            "".join(f"{entry['sha256']}  {entry['path']}\n" for entry in records)
        )

    print(f"{len(records)} real samples, {len(MANIFEST_GAPS)} recorded gaps")
    print(f"{'sample_id':40s} {'bytes':>8s} {'family':12s} {'class':7s} brotli-11")
    for entry, (_, payload, _) in zip(records, sorted(samples, key=lambda item: item[0]["sample_id"])):
        print(
            f"{entry['sample_id']:40s} {entry['byte_count']:8d} "
            f"{entry['media_family']:12s} {entry['size_class']:7s} "
            f"{brotli_ratio(payload):.4f}"
        )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    parser.add_argument(
        "--source-root",
        type=pathlib.Path,
        default=pathlib.Path("/home/dev/.worktrees"),
        help="root the local source paths resolve against",
    )
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()
    if shutil.which("brotli") is None:
        print("brotli is required for the realism signal", file=sys.stderr)
        return 2
    return build(args.out.resolve(), args.source_root.resolve(), args.check)


if __name__ == "__main__":
    sys.exit(main())
