//! CUBR-0101: can a *synthetic* image win `MODE_GEOCM`, and at what size?
//!
//! `geocm_floor` established that a **131,072-byte prefix of real `x-ray` data wins
//! GeoCM, while 65,536 bytes loses to CM2**. That reframes CUBR-0099's negative
//! result: the two synthetic images tried there were 256x256 = 65,536 bytes, exactly
//! the size at which even genuine image data loses. Their shape may never have been
//! the problem.
//!
//! This matters for how CUBR-0101 can be closed. If a synthetic image above the
//! floor wins GeoCM, the fuzz corpus can reach that decode path from *generated*
//! bytes — no fixture committed, no repository weight, and no question about
//! redistributing corpus data. If only real data works, a fixture decision is
//! genuinely required.
//!
//! ```text
//! cargo run --release --example geocm_synth
//! ```

use cubrim::config::EncodeConfig;

fn mode_name(m: u8) -> &'static str {
    match m {
        0 => "CUBE",
        1 => "RAW",
        16 => "CM2",
        17 => "GEOCM",
        _ => "other",
    }
}

/// A smooth radial field with mild deterministic noise — the correlation structure
/// the geometric models are built for.
fn smooth(w: usize, h: usize) -> Vec<u8> {
    let mut v = Vec::with_capacity(w * h);
    for y in 0..h {
        for x in 0..w {
            let base = ((x * x + y * y) / 512) as u8;
            let noise = ((x.wrapping_mul(37) ^ y.wrapping_mul(17)) % 5) as u8;
            v.push(base.wrapping_add(noise));
        }
    }
    v
}

/// A banded gradient: strong vertical structure, weak horizontal detail.
fn bands(w: usize, h: usize) -> Vec<u8> {
    let mut v = Vec::with_capacity(w * h);
    for y in 0..h {
        for x in 0..w {
            v.push((((y * 3) & 0xff) as u8).wrapping_add(((x / 8) & 0x0f) as u8));
        }
    }
    v
}

/// A plasma-like field: several superposed low-frequency ramps, closer to the
/// slowly-varying intensity of a real radiograph than either of the above.
fn plasma(w: usize, h: usize) -> Vec<u8> {
    let mut v = Vec::with_capacity(w * h);
    for y in 0..h {
        for x in 0..w {
            let a = (x * 5 / 7 + y * 3 / 5) as u32;
            let b = ((x + 2 * y) / 3) as u32;
            let c = (x.wrapping_mul(y) / 1024) as u32;
            v.push(((a + b + c) & 0xff) as u8);
        }
    }
    v
}

fn main() {
    let shapes: [(&str, fn(usize, usize) -> Vec<u8>); 3] =
        [("smooth", smooth), ("bands", bands), ("plasma", plasma)];
    // Dimensions bracketing the 64 KiB -> 128 KiB floor measured on real x-ray data.
    let dims = [
        (256usize, 256usize),
        (256, 512),
        (512, 512),
        (512, 1024),
        (1024, 1024),
    ];

    let mut best: Option<(usize, &str)> = None;
    for (name, f) in shapes {
        for (w, h) in dims {
            let data = f(w, h);
            let config = EncodeConfig::v1_default();
            let blob = cubrim::encode_with_config(&data, &config);
            let mode = blob.get(5).copied().unwrap_or(255);
            let rt = cubrim::decode(&blob).map(|d| d == data).unwrap_or(false);
            println!(
                "  {name:<7} {w:>5}x{h:<5} {:>9} B -> mode {:>3} {:<6} rt {}",
                data.len(),
                mode,
                mode_name(mode),
                if rt { "OK" } else { "FAIL" }
            );
            if mode == 17 && rt && best.map(|(b, _)| data.len() < b).unwrap_or(true) {
                best = Some((data.len(), name));
            }
        }
    }

    match best {
        Some((size, name)) => println!(
            "\nsmallest SYNTHETIC input winning MODE_GEOCM: {size} B via '{name}' \
             -- the corpus can reach GeoCM from generated bytes, no fixture needed"
        ),
        None => println!(
            "\nno synthetic shape tested won MODE_GEOCM at any size up to 1 MiB \
             -- reaching GeoCM needs real image data, so a committed fixture is required"
        ),
    }
}
